### ISSUE TITLE
A small problem in wikitime dataset

### ISSUE THREAD

**Issue by Cantoria** [ElliottYan/DS_Temporal#5]
It seems that the columns name doesn't corresponding to columns.(pos1, pos2 and time)
![image](https://user-images.githubusercontent.com/13050299/62908706-ffca0e00-bdab-11e9-81ef-c0acedd66d86.png)

**Comment by ElliottYan** [comment]
Oops, seems that I made mistakes here. Fixed for now. Thanks for your kindly remind.
