### ISSUE TITLE
Some data still missing

### ISSUE THREAD

**Issue by Cantoria** [ElliottYan/DS_Temporal#7]
When i'm trying to train model like MIMLs, i find some data (NYT related) missing. Like:

- vec.bin
- relation2id.txt
- en_vecs/nyt_en_vecs.npy
- en_vecs/en2id.txt

Could you kindly provided data download links? THANKS.

**Comment by ElliottYan** [comment]
OK, sorry about that. 
Seems the problem is that I tried to remove some of the unused data, but some models are still using them.
I will make this work in this weekend.

**Comment by Cantoria** [comment]
Thank you for your updating!
