### ISSUE TITLE
How to train the TempMEM on NYT-10?

### ISSUE THREAD

**Issue by RedVelvetCake21** [ElliottYan/DS_Temporal#9]
I'm trying to use 'MEM_CNN' model on NYT-10, but meet some problems.
Could you provide the .sh file about training the TempMEM on NYT-10?
Thanks!

**Comment by ElliottYan** [comment]
There's a "scripts/" directory in the code-base and I put all .sh scripts there. You can take a look.

**Comment by ElliottYan** [comment]
It has been a quite long time, so I'm not very sure about this. 
If you cannot find it there, please post your scripts and problem, and see whether I can help.
